### ISSUE TITLE
Link to this demo tutorial?

### ISSUE THREAD

**Issue by guillermojleonr** [pbi-tools/report-devops-demo#2]
Hi!. 

Seems like this repository was used as a demo tutorial. Is there any video of this particular demo?

Thanks!

**Comment by mthierba** [comment]
I wasn't able to track down a particular recording for this one. Find a curated list of all presentations/recordings in the public domain with corresponding sources here: https://pbi.tools/resources/#user-groupmeetup-presentations

**Comment by guillermojleonr** [comment]
Thanks!. I'll take a look
